Podfile.lock
depends on https://github.com/dashevo/dashsync-iOS/pull/45
=> Bump bls-signatures-pod to 0.2.4

Podfile.lock
depends on https://github.com/dashevo/dashsync-iOS/pull/47
=> Fix bitcode support in bls-signatures-pod

DashWallet/DWPhoneWCSessionManager.m
Fixed mistype while migrating to the DashSync:
```diff
-    appleWatchData.hasWallet = ! manager.noWallet;
+    appleWatchData.hasWallet = !account; //if there is no account there is no wallet
```
=> Fix watch app when it stuck in 'no wallet' state

DashWallet/DWAmountViewController.m, DashWallet/DWRootViewController.m, DashWallet/DWSendViewController.m, DashWallet/DWSettingsViewController.m, DashWallet/DWTxDetailViewController.m
depends on https://github.com/dashevo/dashsync-iOS/pull/57
=> New price sourcing

DashWallet/Sources/AppleWatch/DWPhoneWCSessionManager.m, DashWallet/Sources/UI/Home/Models/DWSyncModel.m
Use the chainManagerSyncParametersUpdatedNotification to recheck if the sync view should be displayed.
=> Use the chainManagerSyncParametersUpdatedNotification

DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Models/CrowdNode/Services/SendCoinsService.swift
Nil-checking `Error` returned from `publishTransaction` doesn't actually work unless it's nullable. We can make some changes to DashSync to fix that and replace the check with `try` for that matter.
DashSync PR: https://github.com/dashpay/dashsync-iOS/pull/466
Manually
n/a
=> fix: crowdnode error tracking

DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Models/CrowdNode/CrowdNode.swift, DashWallet/Sources/Models/CrowdNode/CrowdNodeConstants.swift, DashWallet/Sources/Models/CrowdNode/Model/ApiCode.swift, DashWallet/Sources/Models/CrowdNode/Model/CrowdNodeError.swift, DashWallet/Sources/Models/CrowdNode/Services/SendCoinsService.swift, DashWallet/Sources/Models/CrowdNode/Services/TransactionObserver.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/CoinsToAddressTxFilter.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/CrowdNodeErrorResponse.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/CrowdNodeRequest.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/CrowdNodeResponse.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/CrowdNodeTopUpTx.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/FullCrowdNodeSignUpTxSet.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/SingleInputAddressSelector.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/SpendableTransaction.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/TransactionFilter.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/TransactionWrapper.swift, DashWallet/Sources/UI/CrowdNode/CrowdNode.storyboard, DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift, DashWallet/Sources/UI/CrowdNode/New Account/NewAccountViewController.swift
When CrowdNode is re-initialized (e.g. due to the app being restarted) we want to restore the current sign-up state.
- Going through the wallet transactions and detecting all that belong to the sign-up process.
- Setting the current CrowdNode sign-up state depending on the available transactions.
- Restoring the account address that was used for sign-up.
Additionally, `swiftformat` was applied to the CrowdNode folders.
manually
n/a
=> [NMI-829] Restoring in-progress/created CrowdNode account

DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Categories/Numbers+Dash.swift, DashWallet/Sources/Models/Coinbase/Coinbase.swift, DashWallet/Sources/Models/Coinbase/domain/Model/remote/CoinbaseUserAccountsResponse.swift, DashWallet/Sources/UI/Coinbase/CoinbaseEntryPoint/Model/CoinbaseEntryPointModel.swift, DashWallet/Sources/UI/Coinbase/Transfer Amount/Model/TransferAmountModel.swift, DashWallet/Sources/UI/Coinbase/Transfer Amount/TransferAmountViewController.swift, DashWallet/Sources/UI/Coinbase/Transfer Amount/Views/ConverterView.swift, DashWallet/Sources/UI/Portal/Model/ServiceDataSource.swift, DashWallet/Sources/UI/Portal/Model/VO/ServiceItem.swift
Fetching user's balance from coinbase returns string value in us_US locale. If user has a different locale we can't parse the balance correctly.
Manually
N/A
=> feat(coinbase): Use UInt64 for coinbase balance instead of String

DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift
To avoid crashes due to authorization being forcefully invoked in non-UI thread, we need to manually authorize the user in UI thread before the deposit is made.
QA
=> fix(crowdnode): authenticate the user before deposit

DashWallet/Sources/UI/Views/SharedViews/Keyboard/NumberKeyboardButton.swift
When app is running on iOS 14 we get a crash due to missing system icon. The one we have been using is only available for iOS 15+.
Manually
N/A
=> fix(ui): Use 'delete.left' icon when running on device with iOS < 15.0

DashWallet/Sources/Models/Coinbase/Coinbase.swift, DashWallet/Sources/Models/CrowdNode/CrowdNode.swift, DashWallet/Sources/Models/Taxes/Taxes.swift, DashWallet/Sources/UI/CrowdNode/Online/CrowdNodeWebViewController.swift, DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodeTransferViewController.swift
We want to mark CrowdNode and Coinbase addresses with a tax category.
- `taxCategory` function is fixed to check the outputs of a transaction for an address.
- CrowdNode address and account address are marked with tax categories.
- Addresses from which transfers to and from Coinbase are made are marked with tax categories.
- Small fixed and cleanup for CrowdNode.
manually
=> feat(crowdnode): Tax category for CrowdNode and Coinbase

DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Models/CrowdNode/CrowdNode+UserDefaults.swift, DashWallet/Sources/Models/CrowdNode/CrowdNode.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/FullCrowdNodeSignUpTxSet.swift, DashWallet/Sources/UI/CrowdNode/CrowdNode.storyboard, DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift, DashWallet/Sources/UI/CrowdNode/Online/ConfirmationTransactionQRController.swift, DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodeTransferViewController.swift, DashWallet/Sources/UI/CrowdNode/Portal/Views/CrowdNodeCell.swift, DashWallet/Sources/UI/CrowdNode/Portal/WithdrawalConfirmationController.swift
Because we request CrowdNode withdrawals in percentage from the total balance, the amount user requested can be different from the received amount.
We want to reflect this in UI as a confirmation dialog showing the final amount.
- UI for the confirmation dialog. On ios 16+ it is a bottom sheet with variable height.
- Calculating the final amount the user will receive.
- Some fixes.
QA
=> feat(crowdnode): Withdrawal confirmation dialog

DashWallet/Sources/Categories/DSTransaction+DashWallet.swift, DashWallet/Sources/UI/Tx/Details/Model/TxDetailModel.swift, DashWallet/Sources/UI/Views/Transitions/Item/Model/TransactionDataItem.swift
Display 'Syncing...' message instead of crashing. 
The core issue is that when we sync the wallet for the first time (or do transaction re-sync) the app crashes, because DashSync returns invalid result for input/output amount. For example, when we are trying to retrieve input/output amount, for the first time, for a transaction that has 9 inputs and 9 outputs we only able to calculate amount for 4 inputs and 5 outputs, because we don’t have all addresses of all funding derivation paths at that moment.
The previous versions had not been crashing, but was showing the wrong amount for some time during the sync, because:
```
uint64_t amount = 1 - 2; // Legal operation in objc
let amount: UInt64 = 1 - 2 // Crash in swift, arithmetic overflow 
````
Manually
N/A
**For repository code-owners and …
=> fix: Display 'Syncing...' message instead of crashing

DashWallet/Sources/Models/CrowdNode/CrowdNode.swift, DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift
In some cases, the wallet restores UserDefaults containing a saved address that doesn't belong to the current wallet.
- If prefs have an address, validate that it belongs to the wallet. Erase prefs if it isn't
- Restore CrowdNode state before assigning an address in the viewModel.
=> fix(crowdnode): Validating preferences before restoring state

DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Models/CrowdNode/CrowdNode.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/SpendableTransaction.swift
Some users see their SignUp transaction rejected by the network. 
This is likely a result of the changes made in https://github.com/dashpay/dashwallet-ios/pull/530
Looks like SignUp transaction is made before peers see the top-up transaction and so it fails.
- `SpendablaTransaction` filter is returned. Since `transactionOutputsAreLocked` check was useless, I replaced it with `relayCount` check. 
It seems like the rejected message is shown when a transaction has 0 relays so it might make sense to check them. This is also similar to how a transaction is considered "spendable" on Android.
The previous issue that Pasta had with signup not going through might have been related to the performance issue, or some network issues. In any case, if topup transaction isn't "spendable", we cannot spend …
=> fix(crowdnode): rejected signup tx

DashWallet/Sources/UI/Setup/SecureWallet/BackupInfo/BackupInfoViewController.swift
Fixed a crash that happens when user tries to backup the wallet from the reminder flow.
QA/Manually 
N/A
=> fix: Crash on backup reminder

DashWallet/Sources/UI/LockScreen/QuickReceive/DWQuickReceiveViewController.m, DashWallet/Sources/UI/Payments/Receive/ReceiveViewController.swift, DashWallet/Sources/UI/Payments/Receive/RequestAmount/Views/DWRequestAmountContentView.m, DashWallet/Sources/UI/Payments/Receive/Views/ReceiveContentView.swift
Fix an issue when tapping 'Share button' closes the screen.
Manually, QA
N/A
=> fix: Tapping share opens share dialog instead of closing the screen

DashWallet/Sources/UI/LockScreen/DWLockScreenViewController.m, DashWallet/Sources/UI/Payment Controller/Enter Amount/ProvideAmountViewController.swift, DashWallet/Sources/UI/Payment Controller/PaymentController.swift, DashWallet/Sources/UI/Payments/Pay/DWBasePayViewController.h, DashWallet/Sources/UI/Payments/Pay/DWBasePayViewController.m
Lock balance on 'ProvideAmountController' when sending from quick scan
Manually
N/A
=> feat: Lock balance on 'ProvideAmountController' when sending from quick scan

DashWallet/Sources/Models/CrowdNode/CrowdNode.swift, DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodeTransferViewController.swift
A user has an issue where tapping on Deposit in CrowdNode consistently causes a crash.
- `showWithdrawalLimitsInfo` moved to `viewDidAppear` as a potential fix.
- Check for 0 balance in `calculateWithdrawalPermil` just in case.
There aren't seem to be any other potential causes that I can detect right now. The crash happens immediately on navigation from Portal to Transfer screen, and not on actual deposit/withdrawal operation.
=> fix(crowdnode): crash on deposit tap

DashWallet/Sources/Models/CrowdNode/CrowdNode.swift, DashWallet/Sources/Models/CrowdNode/TxFilters/CrowdNodeDepositTx.swift, DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift, DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodePortalViewController.swift, DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodeTransferViewController.swift, DashWallet/Sources/UI/CrowdNode/Portal/Model/CrowdNodeTransferModel.swift, DashWallet/Sources/UI/CrowdNode/Portal/WithdrawalLimitsController.swift, DashWallet/Sources/UI/Payments/Amount/BaseAmountViewController.swift, DashWallet/Sources/UI/Views/BaseController/BaseViewController+NetworkReachability.swift
It looks like the crash we have on Deposit happens because of a strict cast in the `CrowdNodeDepositTx.matches` method.
- Change the strict cast to an optional cast
=> fix(crowdnode): optional cast

.gitignore, DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Models/Coinbase/Coinbase+Constants.swift
Coinbase auth info should not be exposed.
- Old Coinbase clientId and secret are removed.
- Changed read logic to read from a separate plist.
- Excluded plists with secrets from the repo.
QA
Developers need to obtain new Coinbase secrets
=> fix: read Coinbase secrets from a plist

DashWallet/Sources/UI/Coinbase/Custodial Swaps/CustodialSwapsViewController.swift, DashWallet/Sources/UI/Coinbase/Custodial Swaps/Model/CustodialSwapsModel.swift
- The "Insufficient funds" error isn't recalculated when the source currency is switched.
- The local currency option shows the source currency value instead of the fiat value.
- Recheck if need to show an error after switching the currency
- Fix the AmountObject for the local currency 
QA
=> fix(coinbase): error and max button behavior

DashWallet/Sources/UI/Home/DWHomeViewController+DWShortcuts.m, DashWallet/Sources/UI/Menu/Settings/DWSettingsMenuViewController.m, DashWallet/Sources/UI/Menu/Settings/LocalCurrency/DWLocalCurrencyViewController.h, DashWallet/Sources/UI/Menu/Settings/LocalCurrency/DWLocalCurrencyViewController.m, DashWallet/Sources/UI/Payments/Amount/BaseAmountViewController.swift
If opened from Settings, the currency picker shows both the Back and the Close buttons and crashes when the Close button is pressed. The Close button is only intended to be shown for a popover mode and its behaviour isn't implemented in the screen mode.
- Make the currency picker aware of it's presentation mode.
- Don't show the close button for Screen presentation mode.
QA
=> fix: crash in the Currency Picker on Close button tap

DashWallet/Sources/UI/Payment Controller/PaymentController.swift, DashWallet/Sources/UI/Uphold/Transfer/Confirm/UpholdConfirmViewController.swift
Showing the PIN dialog in the `.pageSheet` context (iOS 15+) causes the PIN dialog to be cut-off at the edge of the sheet.
- Dismiss confirmation dialogs before requesting PIN.
QA
=> fix: PIN dialog being cut-off

DashWallet/Sources/UI/Payment Controller/Enter Amount/ProvideAmountViewController.swift, DashWallet/Sources/UI/Payment Controller/PaymentController.swift, DashWallet/Sources/UI/Payments/PaymentModels/DWPaymentProcessor.m
If a QR code with an amount specified is scanned, the app shows the confirmation dialog immediately but it should redirect to the "enter amount" screen and allow to modify the amount.
- Redirect to the "enter amount" screen for QR scanned payment intents.
- Pre-set the initial amount on the "enter amount" screen.
QA
=> fix: allow to edit amount after quick scan

DashWallet/Sources/UI/Payments/Receive/Models/DWBaseReceiveModel.m, Shared/Sources/UIImage+Utils.m
On small screens (SE) users have trouble recognizing QR code because the logo is too large.
- Set the logo size at 22% regardless of QR or screen size.
- Increase QR quality for better redundancy. 
QA
=> fix: QR isn't recognized

DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Models/CrowdNode/CrowdNode.swift
Sometimes CrowdNode APY is not updated after the sync is finished. This happens if the CrowdNode state is already restored and the `checkAPY` method is skipped.
- Recheck APY whenever  the`restoreState` is called even if already restored.
QA
=> fix(crowdnode): recheck APY whenever restoreState is called

DashWallet/Sources/UI/Home/Syncing Views/Alert/SyncingAlertContentView.swift
There is an overflow crash caused by the wrong NSUInteger handling.
- Check if substruction will cause overflow
=> fix: overflow crash

DashWallet/Sources/Infrastructure/Currency Exchanger/Data Provider/RatesProvider.swift
Cached rates are not being used right now in the wallet UI
Emit cached rates in the RatesProvider ctor
QA
=> fix: report cached rates on init

DashWallet.xcodeproj/project.pbxproj, DashWallet/Sources/Models/Explore Dash/Extensions/SQLite+ExloreDash.swift, DashWallet/Sources/Models/Explore Dash/Infrastructure/DAO Impl/AtmDAO.swift, DashWallet/Sources/Models/Explore Dash/Infrastructure/DAO Impl/MerchantDAO.swift, DashWallet/Sources/Models/Explore Dash/Infrastructure/Database Connection/ExploreDatabaseConnection.swift, DashWallet/Sources/Models/Explore Dash/Model/Entites/ExplorePointOfUse.swift, DashWallet/Sources/Models/Taxes/Address/AddressUserInfo.swift, DashWallet/Sources/Models/Taxes/Tx/TxUserInfo.swift, DashWallet/Sources/UI/DashPay/Contacts/Models/DWBaseContactsModel.m, Podfile, Podfile.lock
=> fix: xcode 16 support

DashWallet/Sources/Models/Coinbase/Accounts/Account/CBAccount.swift, DashWallet/Sources/Models/Coinbase/Accounts/AccountService.swift, DashWallet/Sources/Models/Coinbase/Coinbase+Error.swift, DashWallet/Sources/Models/Coinbase/Coinbase.swift, DashWallet/Sources/UI/Coinbase/Base/UIViewController+Coinbase.swift, DashWallet/Sources/UI/Coinbase/Base/ViewModel+Coinbase.swift, DashWallet/Sources/UI/Coinbase/Order Preview/OrderPreviewViewController.swift, DashWallet/Sources/UI/Coinbase/Transfer Amount/TransferAmountViewController.swift, DashWallet/Sources/UI/Coinbase/Two Factor Auth/TwoFactorAuthViewController.swift
Transferring from Coinbase to wallet doesn't work
- Change error code that recognizes 2fa required error
- Pass same `idem` for 2fa request as for the primary one
QA
=> fix(coinbase): transfer to wallet fix

DashWallet/Sources/Models/Coinbase/Infrastructure/API/DTOs/Place Buy Order/CoinbasePlaceBuyOrderResponse.swift, DashWallet/Sources/UI/Coinbase/Buy Dash/Confirm Transaction Controller/Model/ConfirmOrderModel.swift
Coinbase Buy Dash doesn't work due to some fields in the order struct not being optional
- Make fields optional
- Rename fields according to updated Coinbase API
QA
=> fix(coinbase): buy and transfer fix

DashWallet/Sources/UI/Payment Controller/Enter Amount/ProvideAmountViewController.swift, DashWallet/Sources/UI/Payments/PaymentModels/DWPaymentProcessor.m, DashWallet/Sources/UI/SwiftUI Components/SendIntro.swift, Podfile.lock
- When scanning a Dash QR code with the camera app, the result is immediate confirmation without ability to modify the amount and without the "Insufficient funds" error being displayed.
- When scanning Dash QR from the app's lockscreen, the full balance can be revealed without authenticating.
- Treat URL payment request the same as QR request, i.e., redirect user to "Send" screen.
- Request authentication for balance reveal
QA
=> fix: deeplink from camera & balance auth
