DashSyncCurrentCommit

Implemented in DashSync: https://github.com/dashevo/dashsync-iOS/pull/83

Update price sourcing logic

---

DashWallet/DWAppDelegate.m

allow starting fetching whether sync progress is 100% or not

Fix background fetch

---

DashWallet.xcodeproj/project.pbxproj
DashWallet.xcodeproj/xcshareddata/xcschemes/DashWalletScreenshotsUITests.xcscheme
DashWallet/Sources/UI/Home/Views/Shortcuts/DWShortcutsView.m
DashWallet/Sources/UI/Main/Views/DWTabBarView.m
DashWallet/Sources/UI/Menu/Forms/DWBaseFormCellModel.h
DashWallet/Sources/UI/Menu/Forms/Selector/DWSelectorFormTableViewCell.m
DashWallet/Sources/UI/Menu/Forms/Switcher/DWSwitcherFormTableViewCell.m
DashWallet/Sources/UI/Menu/Main/Views/DWMainMenuContentView.m
DashWallet/Sources/UI/Menu/Security/DWSecurityMenuViewController.m
DashWallet/Sources/UI/Onboarding/Controllers/DWDemoAppRootViewController.m
DashWallet/Sources/UI/Onboarding/Stubs/DWAdvancedSecurityModelStub.m
DashWallet/Sources/UI/Payments/Amount/DWAmountViewController.m
DashWallet/Sources/UI/Payments/DWPaymentsViewController.m
DashWallet/Sources/UI/Payments/Pay/Cells/DWPayTableViewCell.m
DashWallet/Sources/UI/RootNavigation/DWInitialViewController.m
DashWallet/Sources/UI/Setup/SecureWallet/BackupInfo/DWBackupInfoViewController.m
DashWallet/Sources/UI/Setup/SecureWallet/Seed/DWBackupSeedPhraseViewController.m
DashWallet/Sources/UI/Setup/SecureWallet/Seed/Views/DWPreviewSeedPhraseContentView.m
DashWallet/Sources/UI/Views/SharedViews/Keyboard/DWNumberKeyboardButton.m
DashWallet/Sources/UI/Views/Transitions/Modal/DWModalPresentationController.m
DashWalletScreenshotsUITests/DashWalletScreenshotsUITests-Briding-Header.h
DashWalletScreenshotsUITests/DashWalletScreenshotsUITests.swift
Podfile
Podfile.lock
fastlane/Snapfile
fastlane/SnapshotHelper.swift

Update screenshoting UI Tests

---

DashSyncCurrentCommit
DashWallet/Sources/UI/Payments/Pay/Confirm/DWConfirmPaymentViewController.m
DashWallet/Sources/UI/Payments/Pay/DWBasePayViewController.m
DashWallet/Sources/UI/Payments/PaymentModels/DWPaymentProcessor.h
DashWallet/Sources/UI/Payments/PaymentModels/DWPaymentProcessor.m
DashWallet/Sources/UI/Views/Transitions/Modal/DWModalPresentationController.m
Podfile
Podfile.lock

depends on https://github.com/dashevo/dashsync-iOS/pull/220

Fix invalid app state after cancelling authentication while confirming the payment #NMI-164

---

DashWallet/Sources/UI/Main/Views/DWTabBarView.h
DashWallet/Sources/UI/Main/Views/DWTabBarView.m

Update tabbar appearance on devices without home indicator #NMI-177

---

DashWallet/Sources/UI/Setup/RecoverWallet/DWRecoverModel.m

Reverts dashevo/dashwallet-ios#254

Revert "Fix invalid API usage"

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/Models/Uphold/DWUpholdMainnetConstants.m
DashWallet/Sources/UI/Uphold/Auth/DWUpholdAuthViewController.m
DashWallet/bg.lproj/Localizable.strings
DashWallet/cs.lproj/Localizable.strings
DashWallet/de.lproj/Localizable.strings
DashWallet/el.lproj/Localizable.strings
DashWallet/en.lproj/Localizable.strings
DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/id.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/ja.lproj/Localizable.strings
DashWallet/ko.lproj/Localizable.strings
DashWallet/nl.lproj/Localizable.strings
DashWallet/pl.lproj/Localizable.strings
DashWallet/pt.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings
DashWallet/sk.lproj/Localizable.strings
DashWallet/sq.lproj/Localizable.strings
DashWallet/sv.lproj/Localizable.strings
DashWallet/th.lproj/Localizable.strings
DashWallet/tr.lproj/Localizable.strings
DashWallet/vi.lproj/Localizable.strings
DashWallet/zh-Hans.lproj/Localizable.strings
DashWallet/zh-Hant-TW.lproj/Localizable.strings

Reverts dashevo/dashwallet-ios#275

Revert "changed a few words"

---

DashWallet/Sources/UI/Uphold/Auth/DWUpholdAuthViewController.m
DashWallet/Sources/UI/Uphold/Auth/UpholdAuthStoryboard.storyboard
DashWallet/Sources/UI/Uphold/Root/DWUpholdViewController.m
DashWallet/bg.lproj/Localizable.strings
DashWallet/cs.lproj/Localizable.strings
DashWallet/de.lproj/Localizable.strings
DashWallet/el.lproj/Localizable.strings
DashWallet/en.lproj/Localizable.strings
DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/id.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/ja.lproj/Localizable.strings
DashWallet/ko.lproj/Localizable.strings
DashWallet/nl.lproj/Localizable.strings
DashWallet/pl.lproj/Localizable.strings
DashWallet/pt.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings
DashWallet/sk.lproj/Localizable.strings
DashWallet/sq.lproj/Localizable.strings
DashWallet/sv.lproj/Localizable.strings
DashWallet/th.lproj/Localizable.strings
DashWallet/tr.lproj/Localizable.strings
DashWallet/vi.lproj/Localizable.strings
DashWallet/zh-Hans.lproj/Localizable.strings
DashWallet/zh-Hant-TW.lproj/Localizable.strings

Reverts dashevo/dashwallet-ios#273

Revert "Disable Uphold"

---

DashWallet/Sources/UI/Home/Models/DWHomeModel.m
DashWallet/Sources/UI/Home/Views/DWDashPayProfileView.m
DashWallet/Sources/UI/Menu/Settings/About/DWAboutModel.m
DashWallet/Sources/UI/Views/SharedViews/DWBadgeView.m
DashWallet/bg.lproj/Localizable.strings
DashWallet/cs.lproj/Localizable.strings
DashWallet/de.lproj/Localizable.strings
DashWallet/el.lproj/Localizable.strings
DashWallet/en.lproj/Localizable.strings
DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/id.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/ja.lproj/Localizable.strings
DashWallet/ko.lproj/Localizable.strings
DashWallet/nl.lproj/Localizable.strings
DashWallet/pl.lproj/Localizable.strings
DashWallet/pt.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings
DashWallet/sk.lproj/Localizable.strings
DashWallet/sq.lproj/Localizable.strings
DashWallet/sv.lproj/Localizable.strings
DashWallet/th.lproj/Localizable.strings
DashWallet/tr.lproj/Localizable.strings
DashWallet/vi.lproj/Localizable.strings
DashWallet/zh-Hans.lproj/Localizable.strings
DashWallet/zh-Hant-TW.lproj/Localizable.strings

Fix notifications issues

---

DashWallet/Sources/UI/Home/Views/Shortcuts/DWShortcutCollectionViewCell~ipad.xib
DashWallet/Sources/UI/Home/Views/Shortcuts/DWShortcutsView.m

Improve shortcuts UI for iPad

---

DashWallet.xcodeproj/project.pbxproj

version 5.0.0 b8

---

DashWallet/Sources/Models/DataMigration/DWDataMigrationManager.h
DashWallet/Sources/Models/DataMigration/DWDataMigrationManager.m
DashWallet/Sources/UI/Start/DWStartModel.m
DashWallet/Sources/UI/Start/DWStartViewController.m

Fix migrating old wallet keys

---

DashWallet.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
DashWallet/Sources/UI/Start/DWStartViewController.m

Fix infinite migration stuck when upgrading old keys

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/UI/Setup/RecoverWallet/DWRecoverModel.h
DashWallet/Sources/UI/Setup/RecoverWallet/DWRecoverModel.m
DashWallet/Sources/UI/Setup/RecoverWallet/Views/DWRecoverContentView.m
WatchApp/bg.lproj/Interface.strings
WatchApp/cs.lproj/Interface.strings
WatchApp/de.lproj/Interface.strings
WatchApp/el.lproj/Interface.strings
WatchApp/en.lproj/Interface.strings
WatchApp/es.lproj/Interface.strings
WatchApp/fr.lproj/Interface.strings
WatchApp/id.lproj/Interface.strings
WatchApp/it.lproj/Interface.strings
WatchApp/ja.lproj/Interface.strings
WatchApp/ko.lproj/Interface.strings
WatchApp/nl.lproj/Interface.strings
WatchApp/pl.lproj/Interface.strings
WatchApp/pt.lproj/Interface.strings
WatchApp/ru.lproj/Interface.strings
WatchApp/sk.lproj/Interface.strings
WatchApp/th.lproj/Interface.strings
WatchApp/tr.lproj/Interface.strings
WatchApp/vi.lproj/Interface.strings
WatchApp/zh-Hans.lproj/Interface.strings
WatchApp/zh-Hant-TW.lproj/Interface.strings

allow easy wiping for testers

---

DashWallet/Sources/UI/DashPay/Contacts/DWBaseContactsViewController.m
DashWallet/Sources/UI/DashPay/Profile/DWModalUserProfileViewController.m
DashWallet/Sources/UI/DashPay/Profile/DWUserProfileViewController.h
DashWallet/Sources/UI/DashPay/Profile/DWUserProfileViewController.m
DashWallet/Sources/UI/DashPay/Profile/Model/DWUserProfileModel.h
DashWallet/Sources/UI/DashPay/Profile/Model/DWUserProfileModel.m

Fix accepting contact request on open profile

---

DashWallet/Sources/UI/Home/Models/DWHomeModel.m

Have transactions with a timestamp of 0 be at the top of the list (they are being confirmed)

Transaction Ordering fix.

---

DashWallet/Sources/UI/Setup/RecoverWallet/Views/DWRecoverContentView.m

Don't allow restoring passphrase words in the Wipe screen

---

DashWallet/Sources/UI/Home/Models/DWSyncModel.m

Fix completed sync percent

---

DashWallet/Sources/UI/Home/Models/Transactions/DWTransactionListDataProvider.m
DashWallet/Sources/UI/Menu/Tools/Masternode Keys/DerivationPathKeys/Models/DWDerivationPathKeysModel.m

Fix DashSync update API usage

---

DashWallet/Sources/UI/Setup/RecoverWallet/Views/DWRecoverContentView.m

Fix replacing recovered word: Case insensitive string replace

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Info.plist
DashWallet/Sources/UI/DashPay/Global/DSBlockchainIdentity+DWDisplayName.h
DashWallet/Sources/UI/DashPay/Global/DSBlockchainIdentity+DWDisplayName.m
DashWallet/Sources/UI/Home/Views/Cells/DWTxListHomeCell.m
DashWalletScreenshotsUITests/Info.plist
DashWalletTests/Info.plist
TodayExtension/Info.plist
WatchApp Extension/Info.plist
WatchApp/Info.plist

Display username as transaction title

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Info.plist
DashWallet/Sources/Models/DWEnvironment.m
DashWalletScreenshotsUITests/Info.plist
DashWalletTests/Info.plist
TodayExtension/Info.plist
WatchApp Extension/Info.plist
WatchApp/Info.plist

Switch to devnet-mobile-2

---

DashWallet/Sources/Models/DWGlobalOptions.h
DashWallet/Sources/Models/DWGlobalOptions.m
DashWallet/Sources/UI/DashPay/Contacts/DWRootContactsViewController.m
DashWallet/Sources/UI/Home/Models/DWDashPayModel.m
DashWallet/Sources/UI/Menu/Settings/About/DWAboutModel.m
DashWallet/Sources/UI/Payments/Pay/Models/DWPayModel.m
DashWallet/Sources/UI/Payments/Receive/DWReceiveViewController.m
DashWallet/Sources/UI/Payments/Receive/Models/DWBaseReceiveModel.m
DashWallet/Sources/UI/Payments/Receive/Models/DWReceiveModel.m

Fix inconsistency after creating a new wallet #NMI-378

---

DashWallet/Sources/UI/Menu/Security/DWSecurityMenuModel.h
DashWallet/Sources/UI/Menu/Security/DWSecurityMenuModel.m
DashWallet/Sources/UI/Menu/Security/DWSecurityMenuViewController.m
DashWallet/Sources/UI/Menu/Settings/About/DWAboutViewController.m

Add Hard Reset (ex. Exterminate) debug feature to the security menu

---

DashWallet/Sources/Models/DWGlobalOptions.h
DashWallet/Sources/Models/DWGlobalOptions.m
DashWallet/Sources/UI/Home/Models/DWSyncModel.m
DashWallet/Sources/UI/Menu/Settings/DWSettingsMenuModel.m
DashWallet/Sources/UI/Payments/Amount/Model/Send/DWSendAmountModel.m
DashWallet/Sources/UI/Setup/RecoverWallet/DWRecoverWalletCommand.m

Disable sending during rescan

---

DashWallet.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
DashWallet/Sources/UI/Menu/Main/EditProfile/Avatar/DWAvatarEditSelectorViewController.h
DashWallet/Sources/UI/Menu/Main/EditProfile/Avatar/DWAvatarEditSelectorViewController.m
DashWallet/Sources/UI/Menu/Main/EditProfile/DWEditProfileViewController.m
WatchApp Extension/DWTxInfoDisplayableInterfaceController.swift
WatchApp Extension/DWWatchDataManager.swift

Select profile picture #NMI-303

---

DashWallet.xcodeproj/xcshareddata/xcschemes/WatchApp.xcscheme
DashWallet/Sources/UI/DashPay/Contacts/DWBaseContactsContentViewController.m

Restore content offset after updating contacts screen #NMI-387

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Info.plist
DashWallet/Sources/UI/DashPay/Notifications/DWNotificationsViewController.h
DashWallet/Sources/UI/DashPay/Notifications/DWNotificationsViewController.m
DashWallet/Sources/UI/Home/DWHomeViewController.m
DashWallet/Sources/UI/Home/Models/DWTransactionListDataSource.h
DashWallet/Sources/UI/Home/Models/DWTransactionListDataSource.m
DashWallet/Sources/UI/Home/Views/Cells/DWOpenUserProfileDelegate.h
DashWallet/Sources/UI/Home/Views/Cells/DWTxListHomeCell.m
DashWallet/Sources/UI/Home/Views/DWHomeView.h
DashWallet/Sources/UI/Home/Views/DWHomeView.m
DashWallet/Sources/UI/TxDetail/DWTxDetailFullscreenViewController.m
DashWallet/Sources/UI/TxDetail/DWTxDetailPopupViewController.h
DashWallet/Sources/UI/TxDetail/DWTxDetailPopupViewController.m
DashWallet/Sources/UI/TxDetail/DWTxDetailViewController.h
DashWallet/Sources/UI/TxDetail/DWTxDetailViewController.m
DashWallet/Sources/UI/TxDetail/Views/DWTxDetailContentView.h
DashWallet/Sources/UI/TxDetail/Views/DWTxDetailContentView.m
DashWallet/Sources/UI/TxDetail/Views/DWTxDetailListView.h
DashWallet/Sources/UI/TxDetail/Views/DWTxDetailListView.m
DashWalletScreenshotsUITests/Info.plist
DashWalletTests/Info.plist
TodayExtension/Info.plist
WatchApp Extension/Info.plist
WatchApp/Info.plist

Open user profile from different screens #NMI-365

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Info.plist
DashWallet/Sources/UI/Menu/Main/EditProfile/Upload/DWUploadAvatarModel.m
DashWalletScreenshotsUITests/Info.plist
DashWalletTests/Info.plist
TodayExtension/Info.plist
WatchApp Extension/Info.plist
WatchApp/Info.plist

Fix iCloud production environment 

---

DashWallet/Sources/UI/Menu/Tools/Masternode Keys/DerivationPathKeys/Models/DWDerivationPathKeysModel.h
DashWallet/Sources/UI/Menu/Tools/Masternode Keys/DerivationPathKeys/Models/DWDerivationPathKeysModel.m
DashWallet/bg.lproj/Localizable.strings
DashWallet/cs.lproj/Localizable.strings
DashWallet/de.lproj/Localizable.strings
DashWallet/el.lproj/Localizable.strings
DashWallet/en.lproj/Localizable.strings
DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/id.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/ja.lproj/Localizable.strings
DashWallet/ko.lproj/Localizable.strings
DashWallet/nl.lproj/Localizable.strings
DashWallet/pl.lproj/Localizable.strings
DashWallet/pt.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings
DashWallet/sk.lproj/Localizable.strings
DashWallet/sq.lproj/Localizable.strings
DashWallet/sv.lproj/Localizable.strings
DashWallet/th.lproj/Localizable.strings
DashWallet/tr.lproj/Localizable.strings
DashWallet/vi.lproj/Localizable.strings
DashWallet/zh-Hans.lproj/Localizable.strings
DashWallet/zh-Hant-TW.lproj/Localizable.strings

Allow exporting WIF pk

---

DashWallet/Sources/UI/Uphold/Transfer/OTP/DWUpholdOTPViewController.m

Fix crash while checking for Uphold OTP code #NMI-485

---

DashWallet/Sources/UI/Home/Views/Shortcuts/Models/DWShortcutsModel.m
DashWallet/bg.lproj/Localizable.strings
DashWallet/cs.lproj/Localizable.strings
DashWallet/de.lproj/Localizable.strings
DashWallet/el.lproj/Localizable.strings
DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/id.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/ja.lproj/Localizable.strings
DashWallet/ko.lproj/Localizable.strings
DashWallet/nl.lproj/Localizable.strings
DashWallet/pl.lproj/Localizable.strings
DashWallet/pt.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings
DashWallet/sk.lproj/Localizable.strings
DashWallet/sq.lproj/Localizable.strings
DashWallet/sv.lproj/Localizable.strings
DashWallet/th.lproj/Localizable.strings
DashWallet/tr.lproj/Localizable.strings
DashWallet/vi.lproj/Localizable.strings

Minor updates

---

README.md

issue ref: pod install failure #384
The issue was resolved by switching DashSync from the develop branch
to main branch (HEAD ac83f83f12af923089a2a87723909cf308b5650f at
time of fix).
The fix is to remove the README.md installation instruction to clone
dashsync-ios.git with develop branch switch, so as to clone with
master branch checked out.

pod install failure fix

---

DashWallet/Sources/UI/Home/Models/DWHomeModel.m
DashWallet/Sources/UI/Onboarding/Stubs/DWHomeModelStub.m

Completely disable DashPay #NMI-560

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Info.plist
DashWallet/Sources/UI/Payments/PaymentModels/DWPaymentInputBuilder.m
DashWallet/Sources/UI/Payments/PaymentModels/DWPaymentProcessor.m
DashWallet/Sources/UI/Payments/ScanQR/DWQRScanModel.m

fixes for callback

---

DashWallet/Sources/UI/Home/Views/DWSyncingHeaderView.m

Fix home header background

---

DashWallet/Sources/UI/DashPay/Views/DWDPAvatarView.m

When trying to search a contact the app crashes at the moment when we trying to show a user's avatar
Instead of trying to fetch the image from thumbnail server we load the image directly (in the same way android app does)
Manually
N/A

Load image directly without using thumbnail server as android app does

---

DashWallet/Sources/UI/DashPay/Contacts/GlobalSearch/Model/DWUserSearchModel.m

Adds 'startAfter' param when perform UI-search.

[impl startAfter for UI]

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/Models/CrowdNode/CrowdNode.swift
DashWallet/Sources/Models/CrowdNode/CrowdNodeConstants.swift
DashWallet/Sources/Models/CrowdNode/Model/ApiCode.swift
DashWallet/Sources/Models/CrowdNode/Services/SendCoinsService.swift
DashWallet/Sources/Models/CrowdNode/Services/TransactionObserver.swift
DashWallet/Sources/Models/CrowdNode/TxFilters/CrowdNodeResponse.swift
DashWallet/Sources/Models/CrowdNode/TxFilters/SingleInputAddressSelector.swift
DashWallet/Sources/Models/CrowdNode/TxFilters/SpendableTransaction.swift
DashWallet/Sources/Models/CrowdNode/TxFilters/TransactionFilter.swift
DashWallet/Sources/UI/CrowdNode/CrowdNode.storyboard
DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift
DashWallet/Sources/UI/CrowdNode/New Account/NewAccountViewController.swift
DashWallet/Sources/UI/Explore Dash/DWExploreTestnetViewController.m
DashWallet/Sources/UI/Explore Dash/Views/DWExploreTestnetContentsView.h
DashWallet/Sources/UI/Explore Dash/Views/DWExploreTestnetContentsView.m

As the first step for implementing the CrowdNode integration in the iOS wallet, we need a way to create a new account via CrowdNode blockchain API.
- Added simple UI for an entry point and sign-up initiation
- Created a mechanism for sending transactions with inputs constraint to a reserved account address
- Created a mechanism for waiting for specific transactions (responses from CrowdNode)
Manually
n/a

[NMI-826] CrowdNode sign up via blockchain API

---

.github/workflows/semantic-pull-request.yml

require PRs to follow conventional commits
added a GitHub Action which enforces above

ci: require PRs to follow conventional commits

---

.github/workflows/semantic-pull-request.yml

Action wasn't workijng
fixed it
hasn't
will work now

fix: indentation issues in semantic-pull-request.yml

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/Models/Coinbase/Infrastructure/API/CoinbaseAPIEndpoint.swift
DashWallet/Sources/Models/Coinbase/Infrastructure/API/CoinbaseService.swift
DashWallet/Sources/Models/Coinbase/Use Cases/Place Buy Order/CommitBuyOrder.swift
DashWallet/Sources/Models/Coinbase/Use Cases/Place Buy Order/GetActivePaymentMethods.swift
DashWallet/Sources/Models/Coinbase/Use Cases/Place Buy Order/PlaceBuyOrder.swift
DashWallet/Sources/Models/Coinbase/Use Cases/Swap Trade/CommitSwapTrade.swift
DashWallet/Sources/Models/Coinbase/Use Cases/Swap Trade/GetCoinbaseBaseIDForCurrency.swift
DashWallet/Sources/Models/Coinbase/Use Cases/Swap Trade/RequestSwapTrade.swift
Podfile.lock

Added Buy Dashes use-cases
Added Swap Trade use-cases

Coinbase buy and swap use-cases

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/Models/Explore Dash/Services/ExploreDatabaseSyncManager.swift

Update explore dash database
Manually
N/A

chore(explore-dash): Update explore dash database

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/Models/CrowdNode/CrowdNode+Constants.swift
DashWallet/Sources/Models/CrowdNode/CrowdNode.swift
DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift
DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodeTransferViewController.swift
DashWallet/Sources/UI/CrowdNode/Portal/Model/CrowdNodeTransferModel.swift

UI for withdrawing from CrowdNode.
- Calculating the request value based on the user input and the current CrowdNode balance.
- Minor changes to account for differences between Deposit and Withdrawal flows.
- Updating fiat balance values when user picked another currency option.
QA

feat(crowdnode): Withdraw UI [NMI-837]

---

DashWallet/Sources/UI/Payments/Amount/Model/Send/SendAmountModel.swift
DashWallet/Sources/UI/Views/Transitions/Modal/DWModalPresentationController.h
DashWallet/Sources/UI/Views/Transitions/Modal/DWModalPresentationController.m
DashWallet/Sources/UI/Views/Transitions/Modal/DWModalTransition.m

Send screen UI/UX improvements
Manually
N/A

feat(ui): Send screen improvements

---

DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodeTransferViewController.swift
DashWallet/Sources/UI/CrowdNode/Portal/Model/CrowdNodeTransferModel.swift
DashWallet/Sources/UI/CrowdNode/Portal/Views/FromLabel.swift
DashWallet/Sources/UI/CrowdNode/Portal/Views/KeyboardHeader.swift
DashWallet/bg.lproj/Localizable.strings
DashWallet/cs.lproj/Localizable.strings
DashWallet/de.lproj/Localizable.strings
DashWallet/el.lproj/Localizable.strings
DashWallet/en.lproj/Localizable.strings
DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/id.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/ja.lproj/Localizable.strings
DashWallet/ko.lproj/Localizable.strings
DashWallet/nl.lproj/Localizable.strings
DashWallet/pl.lproj/Localizable.strings
DashWallet/pt.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings
DashWallet/sk.lproj/Localizable.strings
DashWallet/sq.lproj/Localizable.strings
DashWallet/sv.lproj/Localizable.strings
DashWallet/th.lproj/Localizable.strings
DashWallet/tr.lproj/Localizable.strings
DashWallet/uk.lproj/Localizable.strings
DashWallet/vi.lproj/Localizable.strings
DashWallet/zh-Hans.lproj/Localizable.strings
DashWallet/zh-Hant-TW.lproj/Localizable.strings

Localization improvements
Manually
N/A

chore(crowdnode): Localization improvements

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/UI/Coinbase/Account List Controller/AccountListController.swift
DashWallet/Sources/UI/Coinbase/Base.lproj/Coinbase.storyboard
DashWallet/Sources/UI/Coinbase/Buy Dash/Confirm Transaction Controller/Views/ConfirmOrderCells.swift
DashWallet/Sources/UI/Coinbase/CoinbaseEntryPoint/CoinbaseEntryPointViewController.swift
DashWallet/Sources/UI/Coinbase/Custodial Swaps/Order Preview/Views/ConvertCryptoOrderPreviewViews.swift
DashWallet/Sources/UI/Portal/Views/PortalServiceItemCell.swift

Support dark mode on Coinbase integration
Manually, QA
N/A

feat(ui): Dark mode UI enhancements for Coinbase

---

DashWallet/Sources/UI/CrowdNode/CrowdNode.storyboard
DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodePortalViewController.swift
DashWallet/Sources/UI/CrowdNode/Portal/Views/CrowdNodeCell.swift
DashWallet/bg.lproj/Localizable.strings
DashWallet/cs.lproj/Localizable.strings
DashWallet/de.lproj/Localizable.strings
DashWallet/el.lproj/Localizable.strings
DashWallet/en.lproj/Localizable.strings
DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/id.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/ja.lproj/Localizable.strings
DashWallet/ko.lproj/Localizable.strings
DashWallet/nl.lproj/Localizable.strings
DashWallet/pl.lproj/Localizable.strings
DashWallet/pt.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings
DashWallet/sk.lproj/Localizable.strings
DashWallet/sq.lproj/Localizable.strings
DashWallet/sv.lproj/Localizable.strings
DashWallet/th.lproj/Localizable.strings
DashWallet/tr.lproj/Localizable.strings
DashWallet/uk.lproj/Localizable.strings
DashWallet/vi.lproj/Localizable.strings
DashWallet/zh-Hans.lproj/Localizable.strings
DashWallet/zh-Hant-TW.lproj/Localizable.strings

Fix post-merge issues
Manually
N/A

fix: Post-merge issues

---

DashWallet/Sources/UI/Coinbase/Buy Dash/BuyDashViewController.swift
DashWallet/Sources/UI/Coinbase/Buy Dash/Model/BuyDashModel.swift
DashWallet/Sources/UI/Coinbase/Custodial Swaps/CustodialSwapsViewController.swift

Minor Coinbase UI fixes
After 'CoinbaseAmountViewController' introduction we missed a couple things.
Manually
N/A

fix: Coinbase UI

---

DashWallet/Sources/UI/Payments/Amount/Model/AmountObject.swift
DashWallet/Sources/UI/Payments/Amount/Model/BaseAmountModel.swift
DashWallet/Sources/UI/Payments/Amount/Validation/DWAmountInputValidator.m
DashWalletTests/AmountObjectTests.swift

Amount input improvements
Manually, Tests
N/A

feat: Amount input improvements

---

DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodePortalViewController.swift

- Gradient Header is cut short on wide screens
- Gradient bounds set to the parent view width instead of the header width

fix(crowdnode): portal gradient width

---

DashWallet/Sources/UI/Explore Dash/DWExploreTestnetViewController.m
DashWallet/Sources/UI/Explore Dash/Views/DWExploreHeaderView.m
DashWallet/Sources/UI/Explore Dash/Views/DWExploreTestnetContentsView.h
DashWallet/Sources/UI/Explore Dash/Views/DWExploreTestnetContentsView.m

Properly layout elements when user has custom fonts size in settings
Manually
N/A

feat: Properly layout elements when user has custom fonts size in settings

---

DashWallet/Sources/UI/CrowdNode/CrowdNode.storyboard
DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift
DashWallet/Sources/UI/CrowdNode/Online/CrowdNodeWebViewController.swift
DashWallet/Sources/UI/CrowdNode/Online/OnlineAccountDetailsController.swift
DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodePortalViewController.swift
DashWallet/Sources/UI/Payments/Amount/SendAmountViewController.swift

- API address is copied on both API and Primary copy button clicks.
- API address is used instead of Primary to open `FundsOpen` page and is sometimes empty.
- Redirect in the webview controller is triggered on wrong URLs.
- Arithmetic overflow in the `SendAmountViewController.checkLeftoverBalance` method.
- All issues fixed.
- Some refactoring.

fix(crowdnode): Online account issues

---

DashWallet/Sources/UI/Menu/Settings/About/DWAboutViewController.m
DashWallet/Sources/UI/Tx/Details/Model/TxDetailModel.swift

Update infrastructure urls (insight, github)
Manually
N/A

feat: Update infrastructure urls (insight, github)

---

DashWallet/Sources/Models/Explore Dash/Model/Entites/ExplorePointOfUse.swift

Check whether sqlite column of Explore Dash database is null before trying to deserialize it
Manually
N/A

feat: Check whether sqlite column is null before trying to deserialize it

---

DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift

- Address is empty in some cases
- Call `getOrCreate` instead of a simple assignment

fix(crowdnode): create an address if empty

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/Models/Explore Dash/Services/ExploreDatabaseSyncManager.swift
Podfile.lock

Release 6.3.1 preparation
QA
NA

chore: Release preparation

---

DashWallet/Sources/Models/Explore Dash/Services/ExploreDatabaseSyncManager.swift

Merge master into develop
NA
NA
NA

chore: Merge master into develop

---

DashWallet/Sources/UI/Home/Views/Home Balance View/BalanceModel.swift
DashWallet/Sources/UI/Home/Views/Home Balance View/HomeBalanceView.swift
DashWallet/Sources/UI/Home/Views/Home Header View/HomeHeaderView.swift

Update balance on Home Screen during sync
QA/Manually
N/A

fix: Update balance on Home Screen during sync

---

DashWallet/Sources/Application/App.swift
DashWallet/Sources/Models/Coinbase/Coinbase.swift
DashWallet/Sources/UI/Setup/RecoverWallet/DWRecoverModel.m

Reset Coinbase account when user wipes a wallet
-[x] Provide functionality to reset Coinbase account 
QA/Manually 
N/A

feat: Reset Coinbase account when wiping a wallet

---

DashWallet/Sources/UI/Explore Dash/DWExploreTestnetViewController.m
DashWallet/Sources/UI/Explore Dash/Merchants & ATMs/List/AllMerchantLocationsViewController.swift
DashWallet/Sources/UI/Explore Dash/Merchants & ATMs/List/AtmListViewController.swift
DashWallet/Sources/UI/Explore Dash/Merchants & ATMs/List/MerchantListViewController.swift
DashWallet/Sources/UI/Explore Dash/Merchants & ATMs/List/Model/PointOfUseListModel.swift

DashDirect changes
Manually
N/A

feat: DashDirect changes

---

DashWallet/Sources/UI/Explore Dash/Merchants & ATMs/List/MerchantListViewController.swift

Show filters on 'All' tab when loc service is off
QA, Manually
N/A

feat: Explore Dash filters changes

---

DashWallet/Sources/Models/CrowdNode/CrowdNode.swift
DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift
DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodePortalViewController.swift
DashWallet/Sources/UI/CrowdNode/Portal/CrowdNodeTransferViewController.swift
DashWallet/Sources/UI/CrowdNode/Portal/Model/CrowdNodeTransferModel.swift
DashWallet/Sources/UI/CrowdNode/Portal/WithdrawalLimitsController.swift
DashWallet/Sources/UI/Payments/Amount/BaseAmountViewController.swift
DashWallet/Sources/UI/Views/BaseController/BaseViewController+NetworkReachability.swift

To find where the problem is located, we need to collect as many logs as possible from the potential location.

chore(crowdnode): wrap potential crash location in logs

---

DashWallet/Sources/UI/Payment Controller/PaymentController.swift
DashWallet/Sources/UI/Payments/Amount/Model/Send/SendAmountModel.swift
DashWallet/Sources/UI/Payments/Enter Address/EnterAddressViewController.swift
DashWallet/Sources/UI/Payments/Enter Address/Views/PasteboardContentView.swift
DashWallet/Sources/UI/Payments/Pay/Confirm/ConfirmPaymentViewController.swift
DashWallet/Sources/UI/Payments/Pay/DWBasePayViewController.m
DashWallet/Sources/UI/Payments/Pay/Pay.storyboard
DashWallet/Sources/UI/Payments/Pay/PayViewController.swift
DashWallet/Sources/UI/Views/SheetViewController.swift
Podfile.lock

UI fixes and improvements for iOS 15 
QA/Manually
N/A

fix: UI fixes and improvements for iOS 15 

---

DashWallet.xcodeproj/project.pbxproj

chore: Release 7.0.3

---

DashWallet/Sources/Models/Coinbase/Auth/CBAuth.swift
DashWallet/Sources/Models/Coinbase/Infrastructure/API/DTOs/Account/CoinbaseUserAccountData.swift
DashWallet/Sources/UI/Portal/Model/VO/ServiceItem.swift

Reflect Coinbase API changes
QA
N/A

feat(coinbase): Reflect Coinbase API changes

---

DashWallet/Sources/UI/Menu/Security/Advanced Security/DWAdvancedSecurityViewController.m
DashWallet/Sources/UI/Menu/Tools/Masternode Keys/DerivationPathKeys/DerivationPathKeysViewController.swift
DashWallet/Sources/UI/Menu/Tools/Masternode Keys/Overview/KeysOverviewViewController.swift
DashWallet/Sources/UI/Payments/Enter Address/EnterAddressViewController.swift
DashWallet/Sources/UI/Setup/SecureWallet/Seed/DWPreviewSeedPhraseViewController.m

Close sensitive screens when user goes background
QA/Manually
N/A

feat: Close sensitive screens

---

DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/UI/Home/DWHomeViewController+DWShortcuts.m
DashWallet/Sources/UI/Main/MainTabbarController.swift
DashWallet/Sources/UI/Payment Controller/PaymentController.swift
DashWallet/Sources/UI/Payments/Enter Address/EnterAddressViewController.swift
DashWallet/Sources/UI/Payments/Enter Address/Views/PasteboardContentView.swift
DashWallet/Sources/UI/Payments/Pay/DWBasePayViewController.h
DashWallet/Sources/UI/Payments/Pay/DWBasePayViewController.m
DashWallet/Sources/UI/Payments/Pay/PayViewController.swift
DashWallet/Sources/UI/Payments/PaymentsViewController.swift
DashWallet/Sources/Utils/CSVBuilder.swift

refactor: Payment flow

---

DashWallet/es.lproj/Localizable.strings
DashWallet/fr.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.strings
DashWallet/it.lproj/Localizable.stringsdict
DashWallet/pl.lproj/Localizable.strings
DashWallet/ru.lproj/Localizable.strings

chore: update translations

---

DashWallet/Sources/Models/Coinbase/Accounts/AccountRepository.swift

Coinbase request is stuck because it tries to fetch an empty URL.
- Empty URL check

fix(coinbase): don't paginate an empty page

---

DashWallet/AppDelegate.m
DashWallet/Sources/UI/Portal/Model/PortalModel.swift
DashWallet/Sources/UI/Portal/Model/ServiceDataProvider.swift

chore: disable Uphold and Coinbase

---

.gitignore
DashWallet.xcodeproj/project.pbxproj
DashWallet/Sources/Application/Constants.swift
DashWallet/Sources/Models/Coinbase/Coinbase.swift
DashWallet/Sources/Models/Taxes/ZenLedger.swift
DashWallet/Sources/UI/Coinbase/Custodial Swaps/Model/CustodialSwapsModel.swift
DashWallet/Sources/UI/Coinbase/Transfer Amount/Views/ConverterView.swift
DashWallet/Sources/UI/Menu/Tools/ToolsMenuViewController.swift
DashWallet/Sources/UI/Menu/Tools/ZenLedger/ZenLedgerInfoSheet.swift
DashWallet/Sources/UI/Menu/Tools/ZenLedger/ZenLedgerViewModel.swift
DashWallet/Sources/UI/SwiftUI Components/BottomSheet.swift
DashWallet/Sources/UI/SwiftUI Components/TextIntro.swift

- To export user transactions to ZenLedger, all wallet addresses with incoming funds need to be submitted to `/aggregators/api/v1/portfolios/`
- Exporting addresses
- Some SwiftUI component fixes
QA

feat: zenledger export

---

DashWallet/Sources/UI/CrowdNode/CrowdNodeModel.swift

fix(crowdnode): add nil check to fix a crash

---

DashWallet/Sources/UI/Home/Views/HomeView.swift
DashWallet/Sources/UI/Home/Views/HomeViewModel.swift
DashWallet/Sources/UI/SwiftUI Components/Color+DWStyle.swift

- `balanceHeader` doesn't change size if there is "no network" panel
- Overscroll background color is wrong in dark mode

fix: home UI

---

README.md

docs: replaced the shield and the link to it

---

README.md

docs: add release badge
